### ISSUE TITLE
UI Absturz

### ISSUE THREAD

**Issue by SirAres** [eiksch/statev_v2_issues#2549]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Ilija_Taro

**Auftrittszeitpunkt (Datum / Uhrzeit)**

07.08.2022 - 21:46

**Beobachtetes Verhalten**

Dispatch System ( F4 ) geöffnet und gleichzeitig ausversehen auf Tablet ( F3 )
was zum Absturz führte.

**Erwartetes Verhalten**

Das nur das geöffnet wird was man als erste angetippt hat.

**Schritte um den Fehler nachvollziehen zu können**

Dispatch und Tablet gleichzeitig öffnen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

USERINTERFACE FEHLERMELDUNG:

Cannot read property 'items' of undefined
TypeError: Cannot read property 'items' of undefined
    at ClothingInventoryComponent (http://resource/client/ui/index.js:1531303:30)
    at renderWithHooks (http://resource/client/ui/index.js:12730:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:14555:30)
    at beginWork (http://resource/client/ui/index.js:15647:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2424
