### ISSUE TITLE
Fehler beim betreten vom Restaurant in Sandy Shore

### ISSUE THREAD

**Issue by Boing2000** [eiksch/statev_v2_issues#2577]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

****

Bosco_Albert
**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.08.22 ca 17.45
**Beobachtetes Verhalten**

Beim Betreten vom Restaurant ist das Menü gecrashed
**Erwartetes Verhalten**

Menü zur Auswahl: Betreten, Aufschliehen, etc sollte sich öffnen
**Schritte um den Fehler nachvollziehen zu können**

Mit Gebäude durch e interagieren.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Fehler information laut Anzeige: 

SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (http://resource/client/ui/index.js:12184:31)
    at reconcileChildren (http://resource/client/ui/index.js:14329:39)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14902:15)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)

**Comment by DonVitoDiangelo** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2424
