### ISSUE TITLE
Crash beim Raustaben am Produktionscomputer 

### ISSUE THREAD

**Issue by PlayInc89** [eiksch/statev_v2_issues#2640]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**Ryan_Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.11.22
**Beobachtetes Verhalten**

Games Crasht wenn man an der Maschine steht und raustabt

Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at http://resource/client/ui/index.js:1513901:25
    at Array.forEach (<anonymous>)
    at computeMaxItems (http://resource/client/ui/index.js:1513899:15)
    at ProductionApp (http://resource/client/ui/index.js:1513915:5)
    at renderWithHooks (http://resource/client/ui/index.js:13362:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:16262:30)
    at beginWork (http://resource/client/ui/index.js:17535:24)
    at beginWork$1 (http://resource/client/ui/index.js:20815:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20266:22)
    at workLoopSync (http://resource/client/ui/index.js:20202:15)
**Erwartetes Verhalten**

Kein Crash beim Raustaben wenn man am Produktionscomputer steht
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by PlayInc89** [comment]
Edit Sobald ich den Produktionscomputer mit E aufrufen möchte kommt die Fehlermeldung

**Comment by Derison** [comment]
Hey @PlayInc89,
das Problem ist bekannt und wird verursacht durch die fehlenden Item Übersetzungen, die wir im Discord angesprochen haben.
Sollte morgen im Laufe des Vormittags behoben werden.

Trotzdem vielen Dank für deine Meldung! 🙂

**Comment by PlayInc89** [comment]
Supi Danke
