### ISSUE TITLE
Tetris Bugs

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2805]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

26.02 1:47
**Beobachtetes Verhalten**

Habe Tetris gespielt und das UI ist gecrashed
**Erwartetes Verhalten**

Es sollte nicht Crashen
**Schritte um den Fehler nachvollziehen zu können**

Bis 300+ Spielen und hoffen
**Fehlermeldung**

Cannot set property '1' of undefined
TypeError: Cannot set property '1' of undefined
    at http://resource/client/ui/index.js:1563112:61
    at Array.forEach (<anonymous>)
    at http://resource/client/ui/index.js:1563110:15
    at Array.forEach (<anonymous>)
    at updateStage (http://resource/client/ui/index.js:1563109:26)
    at http://resource/client/ui/index.js:1563125:26
    at basicStateReducer (http://resource/client/ui/index.js:13732:51)
    at updateReducer (http://resource/client/ui/index.js:13820:32)
    at updateState (http://resource/client/ui/index.js:14045:20)
    at Object.useState (http://resource/client/ui/index.js:14776:26)
**Optional: Video / Bilder des Fehlers**

https://streamable.com/q5t0nn

**Comment by SHaagmann** [comment]
Noch n anderes Phänomen, was schon öfter aufgefallen ist: https://streamable.com/ikyki2

**Comment by SHaagmann** [comment]
Mal wieder nen UI Crash: 

Cannot set properties of undefined (setting '9')
TypeError: Cannot set properties of undefined (setting '9')
    at http://resource/client/ui/index.js:1622468:61
    at Array.forEach (<anonymous>)
    at http://resource/client/ui/index.js:1622466:15
    at Array.forEach (<anonymous>)
    at updateStage (http://resource/client/ui/index.js:1622465:26)
    at http://resource/client/ui/index.js:1622481:26
    at basicStateReducer (http://resource/client/ui/index.js:13732:51)
    at updateReducer (http://resource/client/ui/index.js:13820:32)
    at updateState (http://resource/client/ui/index.js:14045:20)
    at Object.useState (http://resource/client/ui/index.js:14776:26)

**Comment by SHaagmann** [comment]
Mal wieder UI Crash:

Cannot set properties of undefined (setting '3')
TypeError: Cannot set properties of undefined (setting '3')
    at http://resource/client/ui/index.js:1653012:61
    at Array.forEach (<anonymous>)
    at http://resource/client/ui/index.js:1653010:15
    at Array.forEach (<anonymous>)
    at updateStage (http://resource/client/ui/index.js:1653009:26)
    at http://resource/client/ui/index.js:1653025:26
    at basicStateReducer (http://resource/client/ui/index.js:13732:51)
    at updateReducer (http://resource/client/ui/index.js:13820:32)
    at updateState (http://resource/client/ui/index.js:14045:20)
    at Object.useState (http://resource/client/ui/index.js:14776:26)
