### ISSUE TITLE
UserInterface absturz

### ISSUE THREAD

**Issue by SauerkirscheJM** [eiksch/statev_v2_issues#2823]
Azula Rise

Die Fehlermeldung kam um ca 17:18 Uhr am 05.03.2023

Ich habe beim Juwelier durch die Kategorien der Vorschau durchgeklickt und als ich bei den Ketten ankam tauchte die fehlermeldung auf dem Screenshot auf und ich musste das Spiel neu starten.

Der Juwelier war Poseidon.

Screenshot: (Auflösung: 1920x1080)
![GTA5 2023-03-05 17-17-22](https://user-images.githubusercontent.com/123385988/222975754-a93725af-3457-4966-8685-1797520826a6.png)

Code der Fehelrmeldung:
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at http://resource/client/ui/index.js:1628487:54
    at commitHookEffectListMount (http://resource/client/ui/index.js:18257:36)
    at commitPassiveMountOnFiber (http://resource/client/ui/index.js:19503:19)
    at commitPassiveMountEffects_complete (http://resource/client/ui/index.js:19471:19)
    at commitPassiveMountEffects_begin (http://resource/client/ui/index.js:19461:17)
    at commitPassiveMountEffects (http://resource/client/ui/index.js:19451:13)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:20804:13)
    at flushPassiveEffects (http://resource/client/ui/index.js:20761:24)
    at commitRootImpl (http://resource/client/ui/index.js:20730:15)
    at commitRoot (http://resource/client/ui/index.js:20591:15)

**Comment by simplycach** [comment]
Hast du eventuell ein Video für uns ?

**Comment by SauerkirscheJM** [comment]
nien tut mir leid. Habe sowa nicht nebenbei laufen, das packt mein PC nicht :D
